// Objective-C implementation compiled into the darwin build of the gui
// package. Kept out of the .go preamble so cgo does not compile it more
// than once (which would cause duplicate Objective-C class symbols at
// link time).

#import <AppKit/AppKit.h>

// Forward declaration for the Go-exported function generated by cgo.
// Pulling in _cgo_export.h would create a circular dependency with
// cocoa_darwin.go, so we declare the symbol manually.
extern void yappCocoaHandleReopen(void);

// YappAppDelegate is Yapp's minimal NSApplicationDelegate. It implements
// two reactivation paths, both of which funnel into the same Go callback
// (yappCocoaHandleReopen), which in turn activates the terminal window
// that is actually showing yazi:
//
//  - applicationDidBecomeActive: fires when Yapp transitions from
//    inactive to active, covering Cmd+Tab switches and Dock-icon clicks
//    on an inactive Yapp.
//
//  - applicationShouldHandleReopen: fires on Dock-icon clicks even when
//    Yapp is *already* the active app; in that case didBecomeActive does
//    not fire (no state transition), so without this method a user who
//    clicks Yapp's Dock icon while already looking at Yapp's menu bar
//    would have no way to bring the yazi window back to the front.
//
// Both delegate calls happen on the Cocoa main thread. The Go-side
// handler does the heavy lifting on a goroutine so we don't block here.
@interface YappAppDelegate : NSObject <NSApplicationDelegate>
@end

@implementation YappAppDelegate
- (void)applicationDidBecomeActive:(NSNotification *)notification {
    yappCocoaHandleReopen();
}

- (BOOL)applicationShouldHandleReopen:(NSApplication *)sender
                    hasVisibleWindows:(BOOL)flag {
    yappCocoaHandleReopen();
    return YES;
}
@end

// build_menu installs a minimal main menu with just an Application
// submenu containing Hide / Hide Others / Show All / Quit. Without a
// main menu, Cmd+Q and Cmd+H would not work, and the menu bar area
// next to the Apple logo would be blank when Yapp is frontmost.
static void build_menu(void) {
    NSMenu *mainMenu = [[NSMenu alloc] init];

    NSMenuItem *appMenuItem = [[NSMenuItem alloc] init];
    [mainMenu addItem:appMenuItem];

    NSMenu *appMenu = [[NSMenu alloc] init];
    NSString *appName = [[NSProcessInfo processInfo] processName];

    [appMenu addItemWithTitle:[NSString stringWithFormat:@"Hide %@", appName]
                       action:@selector(hide:)
                keyEquivalent:@"h"];
    NSMenuItem *hideOthers =
        [appMenu addItemWithTitle:@"Hide Others"
                           action:@selector(hideOtherApplications:)
                    keyEquivalent:@"h"];
    [hideOthers setKeyEquivalentModifierMask:
                    (NSEventModifierFlagCommand | NSEventModifierFlagOption)];
    [appMenu addItemWithTitle:@"Show All"
                       action:@selector(unhideAllApplications:)
                keyEquivalent:@""];
    [appMenu addItem:[NSMenuItem separatorItem]];
    [appMenu addItemWithTitle:[NSString stringWithFormat:@"Quit %@", appName]
                       action:@selector(terminate:)
                keyEquivalent:@"q"];

    [appMenuItem setSubmenu:appMenu];
    [NSApp setMainMenu:mainMenu];
}

// yapp_run initialises NSApp, installs the delegate and menu, activates
// the app, and enters the Cocoa event loop. Blocks until [NSApp stop:]
// is called from yapp_stop (or [NSApp terminate:] from the Quit menu).
void yapp_run(void) {
    @autoreleasepool {
        [NSApplication sharedApplication];
        [NSApp setActivationPolicy:NSApplicationActivationPolicyRegular];

        YappAppDelegate *delegate = [[YappAppDelegate alloc] init];
        [NSApp setDelegate:delegate];

        build_menu();

        [NSApp activateIgnoringOtherApps:YES];
        [NSApp run];

        // [NSApp run] returns after stop: is called. Clear the delegate
        // so NSApp releases its reference to our autorelease-pool-owned
        // object before the pool drains.
        [NSApp setDelegate:nil];
    }
}

// yapp_stop breaks out of [NSApp run]. Safe to call from any thread; it
// hops to the main queue to do the work. [NSApp stop:] only takes
// effect on the next event, so we also post a synthetic event to wake
// the run loop immediately.
void yapp_stop(void) {
    dispatch_async(dispatch_get_main_queue(), ^{
        [NSApp stop:nil];
        NSEvent *wake = [NSEvent otherEventWithType:NSEventTypeApplicationDefined
                                           location:NSZeroPoint
                                      modifierFlags:0
                                          timestamp:0
                                       windowNumber:0
                                            context:nil
                                            subtype:0
                                              data1:0
                                              data2:0];
        [NSApp postEvent:wake atStart:YES];
    });
}
